// <auto-generated />
namespace FinanceScraper.DataContexts.StockMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FinanceScraperDataContextsStockMigrationsConfiguration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinanceScraperDataContextsStockMigrationsConfiguration));
        
        string IMigrationMetadata.Id
        {
            get { return "201805061645325_FinanceScraper.DataContexts.StockMigrations.Configuration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
